DEFAULT_PORT = 7777
DEFAULT_IP_ADDRESS = '127.0.0.1'
MAX_CONNECTIONS = 6
MAX_PACKAGE_LENGTH = 1024
ENCODING = 'utf-8'
# Протокол JIM:
ACTION = 'action'
TIME = 'time'
USER = 'user'
ACCOUNT_NAME = 'account_name'
TEXT_MESSAGE = 'text_mess'
MESSAGE = 'message'
SENDER = 'sender'
# Прочие ключи
PRESENCE = 'presence'
RESPONSE = 'response'
ERROR = 'error'
DEF_MODE = 'listen'

